### ISSUE TITLE
Outstanding work for PR 8 Schema to load metasploit-framework

### ISSUE THREAD

**Issue by limhoff-r7** [rapid7/metasploit-cache#12]
The following is the list of assumed tasks to get the schema designed in #8 to be populated with data from metasploit-framework

**NOTE: All constant have the `Metasploit::Cache::` prefixed stripped**

The general design is each class (or superclass) in the schema from #8 will have an ephemeral cache called `*::Ephemeral`, which will have a `#persist` method which takes an ActiveRecord and saves the Metasploit Module `Module`, `Class` or `Object` metadata to that ActiveRecord.  It is the Ephemeral's job to be understand how to convert metasploit-framework's representation of the metadata to the schema's representation of the metadata.  The Ephemeral will also have a resurrectable attribute to get the ActiveRecord.

The work of the `*::Ephemeral#persist` method will be validated by the `Load` class, which will call `*::Ephemeral#persist` and check that the ActiveRecord was saved.

There will also be some mechanism to enumerate all the *::Class given the *::Ancestor and to enumerate all the *::Instance given the *::Class.

## Load `*::Class` (expect `Payload::Staged::Class`) from metasploit-framework
- [x] `Direct::Class::Ephemeral` (#13)
- [x] `Direct::Class::Load` (#13)

### auxiliary
- [x] Load `Auxiliary::Class` from metasploit-framework (#13)

### encoder
- [x] `Encoder::Class` (#15)
- [x] Load `Encoder::Class` from metasploit-framework (#16)

### exploit
- [x] `Exploit::Class` (#17)
- [x] Load `Exploit::Class` from metasploit-framework (#18)

### nop
- [x] `Nop::Class` (#19)
- [x] Load `Nop::Class` from metasploit-framework (#20) 

#### single
- [x] `Payload::Single::Class` (#25)
- [x] Load `Payload::Single::Class` from metasploit-framework (#26)

#### stage
- [x] `Payload::Stage::Class` (#27)
- [x] Load `Payload::Stage::Class` from metasploit-framework (#28)

#### stager
- [x] `Payload::Stager::Class` (#29)
- [x] Load `Payload::Stager::Class` from metasploit-framework (#30)

### post
- [x] `Post::Class` (#21) 
- [x] Load `Post::Class` from metasploit-framework (#22)

### auxiliary
- [x] `Auxiliary::Instance` (#31) 
- [x] `Auxiliary::Instance::Ephemeral`
- [x] `Auxiliary::Instance::Load`
- [x] Load `Auxiliary::Instance` from metasploit-framework

### encoder
- [x] `Encoder::Instance` (#32) 
- [x] `Encoder::Instance::Ephemeral`
- [x] `Encoder::Instance::Load`
- [x] Load `Encoder::Instance` from metasploit-framework

### exploit
- [x] `Exploit::Instance` (#34)
- [x] `Exploit::Instance::Ephemeral`
- [x] `Exploit::Instance::Load`
- [x] Load `Exploit::Instance` from metasploit-framework

### nop
- [x] `Nop::Instance` (#33)
- [x] `Nop::Instance::Ephemeral`
- [x] `Nop::Instance::Load`
- [x] Load `Nop::Instance` from metasploit-framework

#### single
- [x] `Payload::Single::Instance`
- [x] `Payload::Single::Instance::Ephemeral`
- [x] `Payload::Single::Instance::Load`
- [x] Load `Payload::Single::Instance` from metasploit-framework

#### stage
- [x] `Payload::Stage::Instance`
- [x] `Payload::Stage::Instance::Ephemeral`
- [x] `Payload::Stage::Instance::Load`
- [x] Load `Payload::Stage::Instance` from metasploit-framework

#### stager
- [x] `Payload::Stager::Instance`
- [x] `Payload::Stager::Instance::Ephemeral`
- [x] `Payload::Stager::Instance::Load`
- [x] Load `Payload::Stager::Instance` from metasploit-framework

### post
- [x] `Post::Instance`
- [x] `Post::Instance::Ephemeral`
- [x] `Post::Instance::Load`
- [x] Load `Post::Instance` from metasploit-framework

### Load `Payload::Staged::Class` from metasploit-framework
- [x] `Payload::Staged::Class`
- [x] Enumerate `Payload::Staged::Class` from compatible `Payload::Stage::Instance` and `Payload::Stager::Instance`
- [x] Load `Payload::Staged::Class` from metasploit-framework

### Load `Payload::Staged::Instance` from metasploit-framework
- [x] `Payload::Staged::Instance`
- [x] Load `Payload::Staged::Instance` from metasploit-framework

**Comment by limhoff-r7** [comment]
Resolved by #79 or prior PRs
